/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

import { Interface, Contract } from "fuels";
import type { Provider, Account, AbstractAddress } from "fuels";
import type { DaoContractAbi, DaoContractAbiInterface } from "../DaoContractAbi";

const _abi = {
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "(_, _, _, _, _)",
      "components": [
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 18,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 18,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 18,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 18,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 18,
              "typeArguments": null
            }
          ]
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "(_, _, _, _, _, _, _)",
      "components": [
        {
          "name": "__tuple_element",
          "type": 16,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 14,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 18,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "(_, _, _, _, _, _, _, _, _, _)",
      "components": [
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 14,
              "typeArguments": null
            }
          ]
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "(_, _, _, _, _, _, _, _, _, _)",
      "components": [
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 17,
              "typeArguments": null
            }
          ]
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "(_, _, _, _, _, _, _, _, _, _)",
      "components": [
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "__tuple_element",
          "type": 12,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 6,
      "type": "[_; 5]",
      "components": [
        {
          "name": "__array_element",
          "type": 10,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 7,
      "type": "[_; 5]",
      "components": [
        {
          "name": "__array_element",
          "type": 14,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 8,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 9,
      "type": "bool",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 10,
      "type": "enum Identity",
      "components": [
        {
          "name": "Address",
          "type": 14,
          "typeArguments": null
        },
        {
          "name": "ContractId",
          "type": 15,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 11,
      "type": "enum InvalidError",
      "components": [
        {
          "name": "CannotReinitialize",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "DAOIsNotOpen",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "DAOMemberNotExisted",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "SenderIsNotOwner",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "IsNotVotesEnough",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotToEndDate",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "VotingIsNotStart",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "VotingHasEnded",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "ProposalIsNotActive",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "DAOIsNotActive",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "ProposalHasNotRecipient",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "IncorrectAssetId",
          "type": 15,
          "typeArguments": null
        },
        {
          "name": "DaoBalanceNotEnough",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotInWhitelistContributor",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 12,
      "type": "enum Option",
      "components": [
        {
          "name": "None",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Some",
          "type": 13,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        13
      ]
    },
    {
      "typeId": 13,
      "type": "generic T",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 14,
      "type": "struct Address",
      "components": [
        {
          "name": "value",
          "type": 8,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 15,
      "type": "struct ContractId",
      "components": [
        {
          "name": "value",
          "type": 8,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 16,
      "type": "struct DaoConfig",
      "components": [
        {
          "name": "quorum",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "open",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "dao_type",
          "type": 18,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 17,
      "type": "struct Proposal",
      "components": [
        {
          "name": "id",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "owner",
          "type": 14,
          "typeArguments": null
        },
        {
          "name": "proposal_type",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "status",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "recipient",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "start_date",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "end_date",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "created_date",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "allow_early_execution",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "agree",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "disagree",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "executed",
          "type": 9,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 18,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "contributor",
          "type": 10,
          "typeArguments": null
        }
      ],
      "name": "add_contributor_to_whitelist",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "new_member",
          "type": 14,
          "typeArguments": null
        }
      ],
      "name": "add_member",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "proposal_type",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "recipient",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "start_date",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "end_date",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "allow_early_execution",
          "type": 9,
          "typeArguments": null
        }
      ],
      "name": "create_proposal",
      "output": {
        "name": "",
        "type": 18,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "proposal_id",
          "type": 18,
          "typeArguments": null
        }
      ],
      "name": "execute_proposal",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_balance",
      "output": {
        "name": "",
        "type": 18,
        "typeArguments": null
      },
      "attributes": null
    },
    {
      "inputs": [],
      "name": "get_count_member",
      "output": {
        "name": "",
        "type": 18,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_count_proposal",
      "output": {
        "name": "",
        "type": 18,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_dao_info",
      "output": {
        "name": "",
        "type": 2,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "contributors",
          "type": 6,
          "typeArguments": null
        }
      ],
      "name": "get_funds",
      "output": {
        "name": "",
        "type": 1,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "offset",
          "type": 18,
          "typeArguments": null
        }
      ],
      "name": "get_members",
      "output": {
        "name": "",
        "type": 3,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "proposal_id",
          "type": 18,
          "typeArguments": null
        }
      ],
      "name": "get_proposal_by_id",
      "output": {
        "name": "",
        "type": 12,
        "typeArguments": [
          {
            "name": "",
            "type": 17,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "offset",
          "type": 18,
          "typeArguments": null
        }
      ],
      "name": "get_proposals",
      "output": {
        "name": "",
        "type": 4,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "address",
          "type": 14,
          "typeArguments": null
        },
        {
          "name": "proposal_id",
          "type": 18,
          "typeArguments": null
        }
      ],
      "name": "get_user_vote",
      "output": {
        "name": "",
        "type": 12,
        "typeArguments": [
          {
            "name": "",
            "type": 9,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "offset",
          "type": 18,
          "typeArguments": null
        }
      ],
      "name": "get_whitelist_contributors",
      "output": {
        "name": "",
        "type": 5,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "config",
          "type": 16,
          "typeArguments": null
        },
        {
          "name": "members",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "whitelist_contributors",
          "type": 6,
          "typeArguments": null
        }
      ],
      "name": "initialize",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "member",
          "type": 14,
          "typeArguments": null
        }
      ],
      "name": "is_member",
      "output": {
        "name": "",
        "type": 9,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "join",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "leave",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "contributor",
          "type": 10,
          "typeArguments": null
        }
      ],
      "name": "remove_contributor_from_whitelist",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "old_member",
          "type": 14,
          "typeArguments": null
        }
      ],
      "name": "remove_member",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "send_fund",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "proposal_id",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "is_agree",
          "type": 9,
          "typeArguments": null
        }
      ],
      "name": "vote",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": 0,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 1,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 2,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 3,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 4,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 5,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 6,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 7,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 8,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 9,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 10,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 11,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 12,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 13,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 14,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 15,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 16,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 17,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 18,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 19,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 20,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 21,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 22,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 23,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 24,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 25,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 26,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": 27,
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    }
  ],
  "messagesTypes": [],
  "configurables": []
}

export class DaoContractAbi__factory {
  static readonly abi = _abi
  static createInterface(): DaoContractAbiInterface {
    return new Interface(_abi) as unknown as DaoContractAbiInterface
  }
  static connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): DaoContractAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as DaoContractAbi
  }
}
